### ISSUE TITLE
テキストをアコーディオンにしてください

### ISSUE THREAD

**Issue by dninomiya** [satsuki-murata/demo-lp#1]
赤枠をクリックしたら、下の赤枠が開閉するようにしてください。
Sass...以降も同様です

![2017-04-12 21 08 01](https://cloud.githubusercontent.com/assets/5842851/24957229/05cb5772-1fc6-11e7-860e-ab9ec4407eea.png)

**Comment by satsuki-murata** [comment]
@deerboy 
開閉状態の記憶は不要ですか？

**Comment by dninomiya** [comment]
@satsuki-murata 
 不要です！

**Comment by dninomiya** [comment]
@satsuki-murata 
ありがとうございます！
